services:
  orders.api:
    image: ${DOCKER_REGISTRY-}ordersapi
    build:
      context: .
      dockerfile: src/Orders.Api/Dockerfile
    ports:
      - "8080:8080"
      - "8081:8081" 
  
  mongo-express:
    image: mongo-express
    ports:
      - "8088:8081"
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: teste
      ME_CONFIG_BASICAUTH_PASSWORD: teste
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: teste
      ME_CONFIG_MONGODB_URL: mongodb://root:teste@mongo:27017/
    links:
      - mongo
  
  mongo:
    image: mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: teste
    ports:
      - "27017:27017"
    volumes:
      - /volumes/mongoDb:/data/db